### ISSUE TITLE
Running benchmarks on ServiceCollection results in an InvalidCastException

### ISSUE THREAD

**Issue by MisinformedDNA** [DevTeam/Pure.DI#16]
> $  .\Pure.DI.Benchmark.exe ServiceCollection
> Unhandled exception. System.InvalidCastException: Unable to cast object of type 'Pure.DI.Benchmark.Benchmarks.ServiceCollection' to type 'Pure.DI.Benchmark.BenchmarkBase'.
>    at Pure.DI.Benchmark.Program.Main(String[] args) in C:\repos\Pure.DI\Pure.DI.Benchmark\Program.cs:line 26

I'm going to attempt a PR.

**Comment by MisinformedDNA** [comment]
OK, so it also fails because `ServiceCollection` doesn't have a `PureDI()` method.

And if I run `.\Pure.DI.Benchmark.exe Singleton`, I get

> Running benchmark "Singleton".

But then the process ends.

**Comment by NikolayPianikov** [comment]
Please run like `.\Pure.DI.Benchmark.exe --filter *ServiceCollection*`

**Comment by MisinformedDNA** [comment]
That worked. Thanks.

**Comment by NikolayPianikov** [comment]
I've fixed this issue. I used the syntax '.\Pure.DI.Benchmark.exe Singleton' was for profiling. But now it follows a common benchmarks' CLI.

**Comment by NikolayPianikov** [comment]
There is some mess with benchmarks names here, fixed in the last commit
