### ISSUE TITLE
 Generated Code emits Warnings from StyleCop rules

### ISSUE THREAD

**Issue by FreeApophis** [DevTeam/Pure.DI#18]
Sadly the generated code hits quite a few warnings in our codebase

Currently you deactivate the warnings from analyzers and JetBrains one by one by hand:

Instead you should make it clear to the Analyzers that the code is auto-generated and therefore the style is not checked:

https://shishkin.wordpress.com/2008/07/08/stylecop-how-to-ignore-generated-code/

You can add the comment on the start of the file:
```
// <auto-generated/>
```

I am not sure how necessary the file type is, but generated code usually has one of the following file endings, this could also help top avoid warnings from automatic tooling:

*.generated.cs
*.g.cs
*.Designer.cs

**Comment by NikolayPianikov** [comment]
Thx for bug reporting, the fixed version is [1.1.61](https://www.nuget.org/packages/Pure.DI/1.1.61)
