### ISSUE TITLE
Add option to not generate `IServiceCollection` method

### ISSUE THREAD

**Issue by yunusefendi52** [DevTeam/Pure.DI#20]
One use case is for MAUI app, they use MEDI but I only use Pure.DI, but Pure.DI still add the method for IServiceCollection even though it's not needed at least in my use case because the app has reference to MEDI

**Comment by NikolayPianikov** [comment]
A new [nuget package](https://www.nuget.org/packages/Pure.DI/1.1.61) has been published. Please see [this sample](https://github.com/DevTeam/Pure.DI#suppress-generation-of-servicecollection-extensions).
