### ISSUE TITLE
Asp.Net Example

### ISSUE THREAD

**Issue by jwyza-pi** [DevTeam/Pure.DI#29]
Firstly, been watching this repo to see what 2.0 was going to bring and excited to see the possibilities!  Awesome work.

Second, I didn't see it in the list in the readme, but do you have an example for how this might be used in an ASP.Net 6 project.  This seems like a big chunk of what would need to happen to make it AoT compatible (plus the stuff that's coming in .Net 8).

**Comment by NikolayPianikov** [comment]
@jwyza-pi thanks for your interest in this repo! :)

I tried not to add dependencies on any frameworks in v2 or change the concept in any way. But I tried to add enough extension points to make v2 as flexible as possible. To do this, you can change the behavior of the code generator using "Setup hints".

There are many uses for this code generator in ASP.NET. For example, you can use it to build individual compositions of objects. You can then register the corresponding "composition roots" in your _Service Collection_ yourself. In [this](https://github.com/DevTeam/Pure.DI/blob/master/readme/service-collection.md) example, this is done automatically for all roots.

Here is [example](https://github.com/DevTeam/Pure.DI/blob/master/readme/service-provider.md) how to create a _Service Provider_.

All external dependencies (e.g. logger) can be added to the composition as [arguments](https://github.com/DevTeam/Pure.DI/blob/master/readme/arguments.md).

You can use [OnCannotResolve hint](https://github.com/DevTeam/Pure.DI/blob/master/readme/oncannotresolve-hint.md)

If you have a small example of a "template" ASP.NET application that is both simple and shows the essence of ASP.NET, please add it as a zip archive here and describe what you want to get.

I will add this example to [this section](https://github.com/DevTeam/Pure.DI#applications).

**Comment by NikolayPianikov** [comment]
I added [sample Web API](https://github.com/DevTeam/Pure.DI/blob/master/readme/WebAPITemplate.md) using Asp Net Core 7. Maybe it will help in some questions. In any case, please send your example. If we can't do anything with it right away, we will try to figure out how to do it well :)

**Comment by jwyza-pi** [comment]
Thanks, it might be a day or 2, but I'll get you an example scenario.

**Comment by NikolayPianikov** [comment]
@jwyza-pi regarding AOT - this is an ambitious task in my opinion. Now _ServiceCollection_ for web app contains about 300 registrations, some of which are realized by internal types. To create a composition all objects of these types must be able to be created in the composition class. And I have a feeling that you can try to make a fork of the ASP.NET project and type by type carefully build the composition directly in ASP.NET modules. 
- But ASP.NET is a lot of different modules and types can be embedded in different modules, which will add complications
- Some modules may not satisfy [AOT requirements](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/?tabs=net7#limitations-of-native-aot-deployment) and it may be problematic to finalize them to the necessary requirements.
- Some types may be tied to Microsoft DI peculiarities.
- And many other things may appear at the most inopportune time.
