### ISSUE TITLE
Confusing error if parentheses are used when registering a factory method

### ISSUE THREAD

**Issue by AtomicBlom** [DevTeam/Pure.DI#35]
Hi there,

I just spent a good half an hour trying to figure out what I was doing wrong registering a factory method

```csharp
.Bind<ILoggerFactory>().As(Lifetime.Singleton).To((ctx) =>
{
    ctx.Inject(out ILogger logger);
    return new LoggerFactory()
        .AddSerilog(logger);
})
```

This code does not compile with the error
```
Error	DIE003	
The DI.Setup(nameof(CompositionRoot))
        .Bind<ILoggerFactory>().As(Lifetime.Singleton).To((ctx) =>
        {
            ctx.Inject(out ILogger logger);
            return new LoggerFactory()
                .AddSerilog(logger);
        }) is not supported.
```

After a bit of playing around, it seems that the problem is actually the parenthesis `(`ctx`)` => { } in the registration, as they interfere with the source generation and removing them allows the source generator to continue correctly.

Admittedly they're completely superfluous, but I honestly didn't even notice they were there in the sea of red squiggles in Visual Studio.

Environment information:
.net 8.0.101
C# LangVersion default (11)
Pure.DI version 2.0.45 (latest as of this report)

**Comment by NikolayPianikov** [comment]
Thanks for reporting this bug and for finding a workaround. Fixed in version [2.0.46](https://www.nuget.org/packages/Pure.DI/2.0.45). In case of problems with version update, please pay attention to the [Version update](https://github.com/DevTeam/Pure.DI?tab=readme-ov-file#troubleshooting) part.
