### ISSUE TITLE
C#12 collection expressions are not supported

### ISSUE THREAD

**Issue by Serg046** [DevTeam/Pure.DI#46]
C# 12 brings a new way to [instantiate collections](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/collection-expressions) via brackets like this `[1,2,3]`. Currently this is not supported so that `Bind<IDependency>(tags: "tag").To<Dependency>()` works fine but `Bind<IDependency>(tags: ["tag"]).To<Dependency>()` fails with "DIE001 ["tag"] must be a constant value of type System.Object.". Btw, C# treats it as a constant, you can use such a value in attributes, etc.

**Comment by NikolayPianikov** [comment]
In order to accomplish this task, we need to support [Roslyn 4.8](#47)
