### ISSUE TITLE
Enumerable injection issue

### ISSUE THREAD

**Issue by ekalchev** [DevTeam/Pure.DI#52]
I am injecting IEnumerable< IService >. My expectation is to receive IEnumerable with two already created intances but I got instead of instances, factories. So basically the behavior is like I am injecting IEnumerable< Func < IService >>.

Is this by design?

```CSharp

    .Bind<IService>(1).To(ctx =>
    {
        return new StagingService();
    })
    .Bind<IService>(2).To(ctx =>
    {

        return new RegistrationService();
    })

    class ServiceHost
    {
        ServiceHost(IEnumerable<IService> services)
        {
            foreach (IService service in services) // each iteration will create new instance of IService
            {
 
            }

            foreach (IService service in services) // iterating again, does not reuse instances but create a new ones
            {

            }
        }
    }
```

**Comment by NikolayPianikov** [comment]
```c#
using Pure.DI;

var composition = new Composition();
var host = composition.Host;

DI.Setup(nameof(Composition))
    .Bind(1).To<StagingService>()
    .Bind(2).To<RegistrationService>()
    .Root<ServiceHost>("Host");

interface IService;

class StagingService : IService
{
    public StagingService() => Console.WriteLine(GetType());
}

class RegistrationService : IService
{
    public RegistrationService() => Console.WriteLine(GetType());
}

class ServiceHost
{
    public ServiceHost(IEnumerable<IService> services)
    {
        foreach (var service in services)
        {
        }
        
        foreach (var service in services)
        {
        }
    }
}
```

The result is this:

```
StagingService
RegistrationService
StagingService
RegistrationService
```

IEnumerable<T> assumes lazy object resolution. That is, object resolution will occur each time on each new iteration. You have a lot of options.

First, you can "materialize" `services` into a collection before iterating, such as `services.ToList()`:

```c#
class ServiceHost
{
    public ServiceHost(IEnumerable<IService> services)
    {
        var serviceList = services.ToList();
        foreach (var service in serviceList)
        {
        }
        
        foreach (var service in serviceList)
        {
        }
    }
}
```

The result is this:

```
StagingService
RegistrationService
```

Second you can inject the collection right away:

```c#
class ServiceHost
{
    public ServiceHost(IReadOnlyCollection<IService> services)
    {
        foreach (var service in services)
        {
        }
        
        foreach (var service in services)
        {
        }
    }
}
```

**Comment by NikolayPianikov** [comment]
@ekalchev To understand how it works, you can just explore the generated code:

```c#
public ServiceHost Host
{
  get
  {
    IEnumerable<IService> EnumerationOf_perBlockIEnumerable()
    {
      yield return new StagingService();
      yield return new RegistrationService();
    }
			
    IEnumerable<IService> perBlockIEnumerableM05D16di1 = EnumerationOf_perBlockIEnumerable();
    return new ServiceHost(perBlockIEnumerableM05D16di1);
  }
}
```

**Comment by ekalchev** [comment]
The current behavior regarding the injection of IEnumerable<T> seems to differ from the typical handling in other DI containers, where an IEnumerable<T> would be expected to contain a set of instances rather than factories. For cases where lazy initialization is desired, utilizing IEnumerable<Lazy<T>> or IEnumerable<Func<T>> could provide clearer intent and align with common DI patterns.

Consider a scenario where a developer is working with a subset of a codebase that utilizes IEnumerable<T> but isn’t aware that Pure.DI is being used. Without this context, it might not be immediately apparent that IEnumerable<T> is yielding new instances on each iteration, which could lead to unexpected behavior. It’s important for such nuances to be intuitively understood.

**Comment by NikolayPianikov** [comment]
@ekalchev I agree that this behavior is different from classic DI containers. Pure.DI is not a container but a code generator that creates compositions of objects as if you were writing code by hand. Right now it is like this and I think this is the right approach to use `IEnumerable<T>`:

```c#
public ServiceHost Host
{
  get
  {
    IEnumerable<IService> CreateEnumeration()
    {
      yield return new StagingService();
      yield return new RegistrationService();
    }
			
    return new ServiceHost(CreateEnumeration());
  }
}
```

And I'm sure it's the optimal code - that's how I would write it manually :)

_MS DI_ does not work correctly in terms of "laziness" of `IEnumerable<T>`:

```c#
using Microsoft.Extensions.DependencyInjection;

var serviceProvider = new ServiceCollection()
    .AddTransient<IService, StagingService>()
    .AddTransient<IService, RegistrationService>()
    .AddTransient<ServiceHost>()
    .BuildServiceProvider();

serviceProvider.GetRequiredService<ServiceHost>();

interface IService;

class StagingService : IService
{
    public StagingService() => Console.WriteLine(GetType());
}

class RegistrationService : IService
{
    public RegistrationService() => Console.WriteLine(GetType());
}

class ServiceHost
{
    public ServiceHost(IEnumerable<IService> services)
    {
        Console.WriteLine(GetType());

        foreach (var service in services)
        {
        }        
    }
}
```

The result is this:

```
StagingService
RegistrationService
ServiceHost
```

But it should be like this:

```
ServiceHost
StagingService
RegistrationService
```

What if I don't iterate over services at all, or I iterate depending on the condition or I only need the first element? Same thing with repeated iterations. Classic DI containers don't work correctly in terms of `IEnumerable<T>` being "lazy". They create objects that are not needed and at the wrong time. They store them in memory so that they can be returned again in the next iterations. But you can always change this behavior and make it similar to classic DI containers, for example, like this:

```c#
using Pure.DI;

var composition = new Composition();
var host = composition.Host;

// This setup works globally for all setups in this project
DI.Setup("", CompositionKind.Global)
    .Bind<IEnumerable<TT>>().To(ctx =>
    {
        ctx.Inject(out IReadOnlyCollection<TT> items);
        return items;
    });

DI.Setup(nameof(Composition))
    .Bind(1).To<StagingService>()
    .Bind(2).To<RegistrationService>()
    .Root<ServiceHost>("Host");

interface IService;

class StagingService : IService
{
    public StagingService() => Console.WriteLine(GetType());
}

class RegistrationService : IService
{
    public RegistrationService() => Console.WriteLine(GetType());
}

class ServiceHost
{
    public ServiceHost(IEnumerable<IService> services)
    {
        Console.WriteLine(GetType());
        foreach (var service in services)
        {
        }
        
        foreach (var service in services)
        {
        }
    }
}
```

Now works not right from my point of view :), but as in classic DI containers:

```
StagingService
RegistrationService
ServiceHost
```

If you want to override the behavior for your setup only:

```c#
DI.Setup(nameof(Composition))
    .Bind<IEnumerable<TT>>().To(ctx =>
    {
        ctx.Inject(out IReadOnlyCollection<TT> items);
        return items;
    })
    .Bind(1).To<StagingService>()
    .Bind(2).To<RegistrationService>()
    .Root<ServiceHost>("Host");
```

**Comment by ekalchev** [comment]
> Classic DI containers don't work correctly in terms of IEnumerable<T> being "lazy". They create objects that are not needed and at the wrong time

What in IEnumerable imply it should do anything lazy? As I said if you want laziness you should work with IEnumerable < Func<T> > or Lazy< T >. This way you correctly communicate with the readers of the code what would happen when iterating. In the example with IEnumerable< Func< T > > you get a factory. So you have laziness. 

The way classic containers behavior is not because they can't do or don't want to do what you did here. It is just wrong. If I want to make the instantiation lazy I could inject Func<IEnumerable< T > > that won't create the instances until I need them. But you clearly see that behavior in the type you are injecting. If I inject IEnumerable<T> - I explicitly ask non-lazy instantiation of all items T.

Lets say you work with 3rd party library that is not aware what DI container you use. Passing IEnumerable constructed by Pure.DI will not work at all. What code expect the behavior that you current have for IEnumerable?

I understand that you might want factory like behavior but that should not be hidden behind IEnumerable. I already gave example how you can achieve that. 

I am not asking for change or something, just trying to point out this approach is fundamentally wrong. The code base should not be aware if it is run in the context of source generated DI or classic container.

**Comment by ekalchev** [comment]
Thanks for pointing out how to workaround this issue.
