### ISSUE TITLE
do not support Service Dynamic loading from dll Library?

### ISSUE THREAD

**Issue by sgf** [DevTeam/Pure.DI#6]
do not support Service Dynamic loading from dll Library?

**Comment by NikolayPianikov** [comment]
All code are generating on the compile time, so the is no way to add any bindings on the runtime. But you could share some details of your scenario and I will try suggesting some ideas.

**Comment by sgf** [comment]
Dynamic loading is useful in some cases, we consider using dll hot loading in a project for a plugin system. 
But this project also is a great library, compile-time greatly improves performance.

**Comment by NikolayPianikov** [comment]
Yes, I agree, but you could load plugins by your "plugins manager". 

Thank you :)
