### ISSUE TITLE
API for Module Binding.

### ISSUE THREAD

**Issue by cNoNim** [DevTeam/Pure.DI#63]
It will be divided into several issues.

The goal is to bind a class representing a module with properties and methods as dependencies in the composition.

For example we have module composition:
```csharp
public interface IDependency;

public interface IService;

internal class Service(IDependency dependency) : IService;

[Module]
public partial class ServiceModule
{
	[Conditional("DI")]
	private void Setup() =>
		DI.Setup()
		  .Root<IService>("Service")
		  .RootArg<IDependency>("dependency")
		  .Bind().To<Service>();
}
```

The following partial class should be generated:
```csharp
partial class ServiceModule
{
	private readonly ServiceModule _root;

	public ServiceModule() =>
		_root = this;

	internal ServiceModule(ServiceModule parentScope) =>
		_root = (parentScope ?? throw new ArgumentNullException(nameof(parentScope)))._root;

	[Provides]
	public IService Service(IDependency dependency) =>
		new Service(dependency);
}
```

Next we have following application composition in separate assembly:
```csharp
internal class Dependency : IDependency;

public class Program(IService service);

public partial class AppModule
{
	[Conditional("DI")]
	private static void Setup() =>
		DI.Setup()
		  .Root<Program>("Program")
		  .Bind().To<Dependency>()
		  .Bind().To<ServiceModule>();
}
```

The following partial class should be generated:
```csharp
partial class AppModule
{
	private readonly AppModule _root;

	public AppModule() =>
		_root = this;

	internal AppModule(AppModule parentScope) =>
		_root = (parentScope ?? throw new ArgumentNullException(nameof(parentScope)))._root;

	internal Program Program
	{
		get
		{
			var dependency    = new Dependency();
			var serviceModule = new ServiceModule();
			var service       = serviceModule.Service(dependency);
			return new Program(service);
		}
	}
}
```

For now this behavior can be generated by manually describing factories:
```csharp
partial class AppModule
{
	[Conditional("DI")]
	private static void Setup() =>
		DI.Setup()		.Root<Program>(nameof(Program))
		.Bind().To<Dependency>()
		.Bind().To<ServiceModule>()
		.Bind<IService>().To(
			 context =>
			 {
				 context.Inject(out IDependency dependency);
				 context.Inject(out ServiceModule module);
				 return module.Service(dependency);
			 });
}
```

May be we can use the `[Provider]` attribute instead of the `[Module]` attribute, but `*er` is bad naming, imho.

**Comment by cNoNim** [comment]
If the module is placed in the same project, the source generator will not be able to get metadata from source module.

A different mechanism for obtaining metadata should be used to support dependency provision through the source module.

1. It is necessary to distinguish between source modules and binary modules. For this purpose, when generating a module, it is necessary to add a special attribute that says that this module is already generated, i.e. binary.
2. For source module, information about roots should be obtained before composition processing on demand. Perhaps this metadata can be cached for further generation of the module.

**Comment by cNoNim** [comment]
To support module generation without the need for additional attribute CompositionKind.Module can be added.

**Comment by cNoNim** [comment]
The suggested API can be used for bindings and class arguments `.Arg<Module>(“module”)`. It can also be used for root arguments `.RootArg<Module>(“module”)`, where the module parameter will be added to the root if the root requires a dependency provided by the module.

**Comment by NikolayPianikov** [comment]
At this point, a composition from another assembly or another project can be used for this purpose. Compositions from the current project cannot be used in this way due to limitations of the source code generators.

**Comment by NikolayPianikov** [comment]
Examples:
- [Exposed roots](https://github.com/DevTeam/Pure.DI/blob/master/readme/exposed-roots.md)
- [Exposed roots with tags](https://github.com/DevTeam/Pure.DI/blob/master/readme/exposed-roots-with-tags.md)
- [Exposed roots via arg](https://github.com/DevTeam/Pure.DI/blob/master/readme/exposed-roots-via-arg.md)
- [Exposed generic roots](https://github.com/DevTeam/Pure.DI/blob/master/readme/exposed-generic-roots.md)
- [Exposed generic roots with args](https://github.com/DevTeam/Pure.DI/blob/master/readme/exposed-generic-roots-with-args.md)
