### ISSUE TITLE
Simplified factories

### ISSUE THREAD

**Issue by cNoNim** [DevTeam/Pure.DI#64]
This is related to #63 but may be useful on its own.

If we want to bind some dependency to Property or Method of some class, we can describe factory binding.

```csharp
	DI.Setup()
	  .Bind().To<ServiceProvider>()
	  .Bind<IService>().To(
		   context =>
		   {
			   context.Inject(out ServiceProvider provider);
			   return provider.Service;
		   });
```

It is suggested to simplify the description of such dependencies.

Add the [Provides] attribute to the class member.
```csharp
public class ServiceProvider
{
	[Provides]
	public IService Service => new Service();
}
```

And simplify the compositing description.
```csharp
	DI.Setup()
	  .Bind().To<ServiceProvider>();
```

The generator should automatically realize that this instance provides a dependency.

This API involves modifying an existing class.
Therefore, it is suggested to introduce Fluent API.

```csharp
	DI.Setup()
	  .Provides<ServiceProvider>(provider => provider.Service);
```

It's a simplification of manually describing factories and the equivalent of the bindings mentioned at the very beginning.
But the suggested API assumes that the property satisfies all the dependencies that the property type can provide.
If it can be implemented.

**Comment by cNoNim** [comment]
The suggested API can be used for bindings and class arguments `.Arg<ServiceProvider>(“provider”)`. It can also be used for root arguments `.RootArg<ServiceProvider>(“provider”)`, where the provider parameter will be added to the root if the root requires a dependency provided by the module.

**Comment by NikolayPianikov** [comment]
The ``BindAttribute`` attribute was added for this task #64:

```c#
internal class BindAttribute : Attribute
{
    public BindAttribute(
        Type type = default(Type),
        Lifetime lifetime = Lifetime.Transient,
        params object[] tags) { }
}
```

It allows you to specify that bindings will be automatically added to the marked members of a class that participate in bindings. I think it has the same functionality as the `[ProvidesAttribute]` proposed here.

As for the API `Provides<ServiceProvider>(provider => provider.Service)` is a good idea, we should not forget about lifetime, tags and multiple contracts. Basically you would need to do something like `Bind() ... ToMember<T>(instance => instance.Member)`.

I suggest to add `ToMember()` similar as `To()`, I think this way the API will look more coherent as it will allow to add multiple contracts, lifetime and tags.

**Comment by NikolayPianikov** [comment]
Examples:
- [Simplified factory](https://github.com/DevTeam/Pure.DI/blob/master/readme/simplified-factory.md)
- [Bind attribute](https://github.com/DevTeam/Pure.DI/blob/master/readme/bind-attribute.md)
- [Bind attribute with lifetime and tag](https://github.com/DevTeam/Pure.DI/blob/master/readme/bind-attribute-with-lifetime-and-tag.md)
- [Bind attribute for a generic type](https://github.com/DevTeam/Pure.DI/blob/master/readme/bind-attribute-for-a-generic-type.md)
