### ISSUE TITLE
Default lifetime for a type or tag

### ISSUE THREAD

**Issue by cNoNim** [DevTeam/Pure.DI#66]
There's already a way to control lifetime for provided bindings: https://github.com/DevTeam/Pure.DI/blob/master/readme/default-lifetime.md.

It would be nice if there was a way to define lifetime for auto-binding for all classes implementing the interface or having an attribute.

**Comment by NikolayPianikov** [comment]
Examples:
- [Default lifetime for a type](https://github.com/DevTeam/Pure.DI/blob/master/readme/default-lifetime-for-a-type.md)
- [Default lifetime for a type and a tag](https://github.com/DevTeam/Pure.DI/blob/master/readme/default-lifetime-for-a-type-and-a-tag.md#default-lifetime-for-a-type-and-a-tag)
