### ISSUE TITLE
Scoped lifetime does not work (as expected) in a WebApi project

### ISSUE THREAD

**Issue by duongphuhiep** [DevTeam/Pure.DI#70]
[This demo](https://github.com/duongphuhiep/PureDIBugDemo) shows the issue:

* Each request coming to the [CounterCotroller](https://github.com/duongphuhiep/PureDIBugDemo/blob/master/WebAPI/Controllers/CounterController.cs#L13) would use the [CounterService] to increase the counter then return the Count value.
* The [CounterService is registered as scoped](https://github.com/duongphuhiep/PureDIBugDemo/blob/master/WebAPI/Composition.cs#L24), Hence, I expected that each request will create a new [CounterService] **but it was not the case, all requests shared the same [CounterService] as if it was a Singleton.**

You can run the following (failed) test to reproduce the issue:

https://github.com/duongphuhiep/PureDIBugDemo/blob/master/WebAPI.Tests/BasicTests.cs

Kind regards

[CounterService]: https://github.com/duongphuhiep/PureDIBugDemo/blob/master/WeatherForecast/CounterService.cs

**Comment by NikolayPianikov** [comment]
You are correct and thank you for your research. 

There's question #43. That's what it's about. I have not found an extension point that would allow to build into the Scope mechanism for ASP.NET. I've read several related posts and they discuss this possibility. Maybe I'm missing something and you know of a way to do this?

Anyway I'll see if something has changed and there are extension points.

**Comment by NikolayPianikov** [comment]
Here's [an example](https://github.com/DevTeam/Pure.DI/blob/master/readme/auto-scoped.md). We need to intercept session creation and do something like this:
```c#
var session = new Composition(baseComposition);
```
