### ISSUE TITLE
Resolve Multiple Binds

### ISSUE THREAD

**Issue by sgf** [DevTeam/Pure.DI#9]
like this:

var objs=ResolveAll<T>();

**Comment by NikolayPianikov** [comment]
In this case, we need to know all types of root instances. Therefore, we must mark them somehow. The second question is what to do with generics. Let's say you registered an `IService<TT>` type. What type should be allowed there: `IService<int>`, `IService<string>` or something else? The simplest way is to specify all required root types as a list of constructor arguments of some composition root type, for example:
```
class CompositionRoot
{
     CompositionRoot(ISomeService someService, IService<string> stringService) {}
}
```

**Comment by sgf** [comment]
i just need slove the sample poblem.
looks like this:

OnePage:IPage
TwoPage:IPage
ThreePage:IPage
FourPage:IPage

and i need create all instances of them.

**Comment by NikolayPianikov** [comment]
Please see this example:

```C#
// The application entry point and the composition root.
// This is the only place in the application where the object graph is created.
using System.Collections.Generic;
using Pure.DI;

namespace Abc;

internal class Program
{
    public static void Main() => Composer.Resolve<Program>().Run();

    private readonly IEnumerable<IPage> _pages;
    
    public Program(IEnumerable<IPage> pages) => _pages = pages;

    private void Run()
    {
        foreach (var page in _pages)
        {
            // do something
        }
    }
}


internal static partial class Composer
{
    private static void Setup() => DI.Setup()
        .Bind<IPage>(1).To<OnePage>()
        .Bind<IPage>(2).To<TwoPage>()
        .Bind<IPage>(3).To<ThreePage>()
        .Bind<IPage>(4).To<FourPage>()
        .Bind<Program>().To<Program>();
}

internal interface IPage { }
internal class OnePage : IPage { }
internal class TwoPage:IPage { }
internal class ThreePage:IPage { }
internal class FourPage:IPage { }
```

_Program_ is like a "Composition root" there

**Comment by sgf** [comment]
> Please see this example:
> 
> _Program_ is like a "Composition root" there


thank you,it looks so magic code.
This seems to be some kind of design pattern.
Forgive my ignorance.

**Comment by NikolayPianikov** [comment]
This is not a magic, but it is just a [C# code generator](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview) :) I'm always happy to help you!

**Comment by NikolayPianikov** [comment]
You can find a lot others [there](https://github.com/amis92/csharp-source-generators). And this is [another one](https://github.com/DevTeam/Immutype) interesting :)
